// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TypeShape.Core")>]
[<assembly: AssemblyProductAttribute("TypeShape")>]
[<assembly: AssemblyDescriptionAttribute("Practical Generic Programming in F#")>]
[<assembly: AssemblyVersionAttribute("4.0.0")>]
[<assembly: AssemblyFileVersionAttribute("4.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TypeShape.Core"
    let [<Literal>] AssemblyProduct = "TypeShape"
    let [<Literal>] AssemblyDescription = "Practical Generic Programming in F#"
    let [<Literal>] AssemblyVersion = "4.0.0"
    let [<Literal>] AssemblyFileVersion = "4.0.0"
