// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TypeShape")>]
[<assembly: AssemblyProductAttribute("TypeShape")>]
[<assembly: AssemblyDescriptionAttribute("Practical Generic Programming in F#")>]
[<assembly: AssemblyVersionAttribute("2.14")>]
[<assembly: AssemblyFileVersionAttribute("2.14")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TypeShape"
    let [<Literal>] AssemblyProduct = "TypeShape"
    let [<Literal>] AssemblyDescription = "Practical Generic Programming in F#"
    let [<Literal>] AssemblyVersion = "2.14"
    let [<Literal>] AssemblyFileVersion = "2.14"
