// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TypeShape")>]
[<assembly: AssemblyProductAttribute("TypeShape")>]
[<assembly: AssemblyDescriptionAttribute("Practical Generic Programming in F#")>]
[<assembly: AssemblyVersionAttribute("6.1.1")>]
[<assembly: AssemblyFileVersionAttribute("6.1.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TypeShape"
    let [<Literal>] AssemblyProduct = "TypeShape"
    let [<Literal>] AssemblyDescription = "Practical Generic Programming in F#"
    let [<Literal>] AssemblyVersion = "6.1.1"
    let [<Literal>] AssemblyFileVersion = "6.1.1"
