// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("TypeShape.CSharp")]
[assembly: AssemblyProductAttribute("TypeShape")]
[assembly: AssemblyDescriptionAttribute("Practical Generic Programming in F#")]
[assembly: AssemblyVersionAttribute("3.0")]
[assembly: AssemblyFileVersionAttribute("3.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "TypeShape.CSharp";
        internal const System.String AssemblyProduct = "TypeShape";
        internal const System.String AssemblyDescription = "Practical Generic Programming in F#";
        internal const System.String AssemblyVersion = "3.0";
        internal const System.String AssemblyFileVersion = "3.0";
    }
}
